language: node_js
sudo: false
# cache:
#   yarn: true
#   directories:
#     - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8

matrix:
  include:
    - os: linux
      node_js: '9'
      compiler: clang
      env:
      addons:
         apt:
            sources: [ 'ubuntu-toolchain-r-test','llvm-toolchain-precise-3.8', 'gcc-multilib', 'g++-multilib', 'libsqlite3-dev' ]
            packages: [ 'clang-3.8' ]
    - os: osx
      node_js: '9'

before_install:
  - export CAMV_VERSION=$(node -e "console.log(require('./package.json').version);")
  - uname -s
  - echo '${CXX} ${CC}'
  - if [[ $(uname -s) == 'Linux' ]]; then
      export CXX="clang++-3.8";
      export CC="clang-3.8";
      export DEPLOY_FILE=out/make/CAMV-linux-x64-${CAMV_VERSION}.zip;
    elif [[ $(uname -s) == 'Darwin' ]] ; then
      export DEPLOY_FILE=out/make/CAMV-darwin-x64-${CAMV_VERSION}.zip;
    fi;
  - "npm i -g npm@5.5.1"
  - "npm i -g yarn"
  - "npm --version"
  - "yarn --version"

install:
  # - travis_wait 30 yarn
  - travis_wait 30 npm install

script:
  # - travis_wait 30 yarn run make
  - travis_wait 30 npm run make
  - ls -lh out/make/

deploy:
  provider: releases
  api_key:
    secure: KG2ZcIrdF82bWGCiKu1lDZMuC6X6XbKit6dJymPVJ0bKiSuxpHl12ZywKKXb/qzrOqNytoFIsiLAXYFezxgv5SHmTLZl7+e+QmL3egKLTMwaLcHW8pGZNHXiiuVna3XYcxDkcPiYpcjtRU71kYUkA6JA5AH4jNaTqfWvX/hL1EetloiU4tMm6jqHnYMiwCVkhkviALZqlNK3ORYZnF3n5AU4MIz3m03tT45T5zfSelPM0JLsIjKYKqzadnCMTFQbpiscxTcjzx8vqUTj9puX/1QOr74kmTNuk66NsutN9I9c9ix81qtV7A5+B+30Luzq5SIy572WvVHxssLCWQr+V+NJZf8+YQhvup06zztkh/HVgn4NaT1FUYD1ePaDBsky3myIYTQ6nvGEGAjwcBFO6+6FTkXxiYgbDbnKUX6lkrI3RFnl/8G0UpcFU1wLVSX4cuz/BPTmPompzsB9i0naLEVaj0yDwYze7ohOtiIEN8l4Ss9l+jNcwBElbK6rSqevD0Gg9riG5mZ+JLt97W7dU2jVAihDKi3Aig4VR/+w6V783b64I0Rd3zs5zxQe+zIXTVH2gwtNYp92cAWPSaBbYTCy4HnKgu74Ww60sVQ3qCrITqrajc6DS3x9MqpfxZb3dfFEIL5gen/xUrkTlfVmSE+R6AQtNrt1XiGHqQzHhxs=
  file:
    - $DEPLOY_FILE
  skip_cleanup: true
  on:
    repo: white-lab/CAMV
    tags: true
