language: node_js
sudo: false
cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - clang-3.8

matrix:
  include:
    - os: linux
      node_js: '8'
      compiler: clang
      env:
      addons:
         apt:
            sources: [ 'ubuntu-toolchain-r-test','llvm-toolchain-precise-3.8', 'gcc-multilib', 'g++-multilib', 'libsqlite3-dev' ]
            packages: [ 'clang-3.8' ]
    - os: osx
      node_js: '8'

before_install:
  - export CAMV_VERSION=$(node -e "console.log(require('./package.json').version);")
  - uname -s
  - echo '${CXX} ${CC}'
  - if [[ $(uname -s) == 'Linux' ]]; then
      export CXX="clang++-3.8";
      export CC="clang-3.8";
      export DEPLOY_FILE=out/make/CAMV-linux-x64-${CAMV_VERSION}.zip;
    elif [[ $(uname -s) == 'Darwin' ]] ; then
      export DEPLOY_FILE=out/make/CAMV-darwin-x64-${CAMV_VERSION}.zip;
    fi;
  - "npm i -g npm@5.0.3"
  - "npm i -g yarn@0.27.5"
  - "npm --version"
  - "yarn --version"

install:
  - travis_wait 30 yarn
  # - travis_wait 30 npm install --no-shrinkwrap

script:
  - travis_wait 30 yarn run make
  # - travis_wait 30 npm run make
  - ls -lh out/make/

deploy:
  provider: releases
  api_key:
    secure: "lPngG1881+zGBtHi1UlpHm25btSeqi9oOGTot2glRweBEqHMfTlu2uqyKTSbj9gpCgKs8xrJst5dhbsHJzOC49V0iX903a6RIUAb4izU1U3Td5n8BivrhmkvH5oI2XU064qOAyETZwwahoDWfM+T+TXT5tbqIOPoanmNac85Gjir4JiSUa3p/E6IXWYULgAMtTnuc/ZIRcGbt9oaLEr1k9BPs50kRbXQJxQL+QAEZAs90wQyiTB35478GCEREGqe3Swt75LpstsMi3V+kpDfXG792zfY6aLkniAjs5BAyyFgDmuFnrm3T6sXgcb5tXeMVIV3J8dtLWMKCFk94i9rrGmHF9XFA5/5JOv1bXX8lqUjFE2cCNrUUXE1EXaj9cFxhmivrFgXlGwsF+AhC/XKv5CIDUsoFZUfL7voq39XcTrbFEluV194q6F2zRuQViT/8NJHAQlNg6EUYHKmEFF0TFLGDamP+xMH2WxhxCMWPbyo3b6OnvMdvlPsAfhHE56zlUhPUaPN1wBkE3pZaO1hH8Uj7mD2YIawIHTBN7nfh9R/ReknQBCqYzyAp0oc5aS0ZnD4KFaj/R4TOgat/oSLOsGpRli7/DDHiIqT5v9lYUAD6rPhPKhfRCJT/1lvdupw7iCldfC1qvIajNTb7QGQ32G7EPI8MlgZQpqo+Dcwv2o="
  file:
    - $DEPLOY_FILE
  skip_cleanup: true
  on:
    repo: white-lab/CAMV
    tags: true
