version: Build {build}

skip_non_tags: true

environment:
    matrix:
        - nodejs_version: "8.1.0"
          platform: x64

install:
    - ps: Update-NodeJsInstallation $env:nodejs_version $env:platform
    - "node --version"
    - "npm --version"
    - "npm install"
    - "npm install bower -g"
    - "bower install"
    - ps: $pycamverter_version = git ls-remote --tags git://github.com/white-lab/pycamverter.git | cut -f 2 | cut -d / -f 3 | cut -d ^ -f 1 | tail -n1
    - ps: Start-FileDownload https://github.com/white-lab/pycamverter/releases/download/${pycamverter_version}/PyCAMVerter.exe

# test_script:
#     - npm test

build_script:
    - npm run make
    - "ls -lh out/make/"

artifacts:
    - path: "out/make/CAMV-win32-x64-*.zip"

deploy:
    - provider: GitHub
      description: "Computer Assisted Manual Validation for Mass Spectrometry Proteomics"
      artifact: /CAMV-.*\.zip/
      draft: false
      prerelease: false
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: Vt90BNYB5BI/GtFTilnFdNNEC8T+/szE6cmO3M3gpMaMRXzE4p+XNdAHyymTxnJN
